---
# tasks file for service configuration
- name: Copy Systemd service template
  template:
    src: systemd_sonarr.service.j2
    dest: /etc/systemd/system/sonarr.service
    owner: root
    group: root
    mode: 0644

- name: Start sonarr service
  systemd:
    state: started
    enabled: yes
    name: sonarr.service
    daemon_reload: yes
